app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questionnaire/', include('questionnaire.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questionnaire/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.urls import path

from questionnaire.utils import GetPDF, get_survey_result_csv
from questionnaire.views import ConfirmView, IndexView, SurveyCompleted, SurveyDetail
# from questionnaire.views.survey_result import serve_result_csv

app_name = 'questionnaire'

urlpatterns = [
    path("", IndexView.as_view(), name="survey-list"),
    path("<slug:slug>", SurveyDetail.as_view(), name="survey-detail"),
    path("get_result_pdf/<int:id>", GetPDF.as_view(), name="get_result_pdf"),
    path("view_result_pdf/<int:id>", GetPDF.as_view(), name="view_result_pdf"),

    # url(r"^csv/(?P<primary_key>\d+)/", serve_result_csv, name="survey-result"),
    url(r"^csv/(?P<primary_key>\d+)/", get_survey_result_csv, name="survey-result"),
    url(r"^(?P<slug>\d+)/completed/", SurveyCompleted.as_view(), name="survey-completed"),
    path("<slug:slug>-<int:step>/", SurveyDetail.as_view(), name="survey-detail-step"),
    url(r"^confirm/(?P<uuid>\w+)/", ConfirmView.as_view(), name="survey-confirmation"),
]

questionnaire/models/answer.py
"""
    These type-specific answer models use a text field to allow for flexible
    field sizes depending on the actual question this answer corresponds to any
    "required" attribute will be enforced by the form.
"""

import logging

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

from .question import Question
from .response import Response

LOGGER = logging.getLogger(__name__)


class Answer(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name=_("Question"), related_name="answers")
    response = models.ForeignKey(Response, on_delete=models.CASCADE, verbose_name=_("Response"), related_name="answers")
    created = models.DateTimeField(_("Creation date"), auto_now_add=True)
    updated = models.DateTimeField(_("Update date"), auto_now=True)
    body = models.TextField(_("Content"), blank=True, null=True)

    def __init__(self, *args, **kwargs):
        try:
            question = Question.objects.get(pk=kwargs["question_id"])
        except KeyError:
            question = kwargs.get("question")
        body = kwargs.get("body")
        if question and body:
            self.check_answer_body(question, body)
        super().__init__(*args, **kwargs)

    @property
    def values(self):
        if self.body is None:
            return [None]
        if len(self.body) < 3 or self.body[0:3] != "[u'":
            return [self.body]
        # We do not use eval for security reason but it could work with :
        # eval(self.body)
        # It would permit to inject code into answer though.
        values = []
        raw_values = self.body.split("', u'")
        nb_values = len(raw_values)
        for i, value in enumerate(raw_values):
            if i == 0:
                value = value[3:]
            if i + 1 == nb_values:
                value = value[:-2]
            values.append(value)
        return values

    def check_answer_body(self, question, body):
        if question.type in [Question.RADIO, Question.SELECT, Question.SELECT_MULTIPLE]:
            choices = question.get_clean_choices()
            if body:
                if body[0] == "[":
                    answers = []
                    for i, part in enumerate(body.split("'")):
                        if i % 2 == 1:
                            answers.append(part)
                else:
                    answers = [body]
            for answer in answers:
                if answer not in choices:
                    msg = f"Impossible answer '{body}'"
                    msg += f" should be in {choices} "
                    raise ValidationError(msg)

    def __str__(self):
        return f"{self.__class__.__name__} to '{self.question}' : '{self.body}'"

questionnaire/models/bg_image.py
from django.db import models


class BGImage(models.Model):
    name = models.TextField(max_length=256, null=False, blank=False)
    image = models.ImageField(verbose_name='background image site', null=True, blank=True)
    image_pdf = models.ImageField(verbose_name='background image pdf (size about: 700 x 800px)', null=True, blank=True)
    image_code = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "background image"
        verbose_name_plural = "background images"

    def __str__(self):
        return str(self.name)

questionnaire/models/category.py
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from .survey import Survey
from .survey_template import SurveyTemplate


class Category(models.Model):

    name = models.CharField(_("Name"), max_length=400)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, verbose_name=_("Survey"), related_name="categories", null=True)
    survey_template = models.ForeignKey(SurveyTemplate, on_delete=models.CASCADE, verbose_name=_("Survey"), related_name="categories", null=True)
    order = models.IntegerField(_("Display order"), blank=True, null=True)
    description = models.CharField(_("Description"), max_length=2000, blank=True, null=True)

    class Meta:
        # pylint: disable=too-few-public-methods
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def __str__(self):
        return self.name

    def slugify(self):
        return slugify(str(self))

questionnaire/models/email_text.py
from django.db import models


class EmailText(models.Model):
    name = models.TextField(max_length=256, null=False, blank=False)
    subject = models.TextField(max_length=256, null=True, blank=True, default='survey results')
    body = models.TextField(max_length=256, null=True, blank=True, default='survey results')

    class Meta:
        verbose_name = "email text"
        verbose_name_plural = "email texts"

    def __str__(self):
        return str(self.name)

questionnaire/models/global_text.py
from django.db import models


class GlobalText(models.Model):
    name = models.TextField(max_length=256, null=False, blank=False)
    question = models.TextField(max_length=256, null=True, blank=True, default='question')
    answer_this_part = models.TextField(max_length=1024, null=True, blank=True, default='answer this part')
    button_next = models.TextField(max_length=64, null=True, blank=True, default='Next')
    button_done = models.TextField(max_length=64, null=True, blank=True, default="I'm done!")
    button_previous_page = models.TextField(max_length=64, null=True, blank=True, default="Previous page")
    button_start_over = models.TextField(max_length=64, null=True, blank=True, default="Start over")
    survey_submitted = models.TextField(max_length=512, null=True, blank=True, default="Survey submitted")
    answers_have_been_saved = models.TextField(max_length=1024, null=True, blank=True, default="Thanks! Your answers have been saved") # noqa
    you_can_change_answers = models.TextField(max_length=1024, null=True, blank=True, default="You can always come back and change them.") # noqa

    class Meta:
        verbose_name = "global text"
        verbose_name_plural = "global texts"

    def __str__(self):
        return str(self.name)

questionnaire/models/response.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from .survey import Survey

try:
    from django.conf import settings

    if settings.AUTH_USER_MODEL:
        user_model = settings.AUTH_USER_MODEL
    else:
        user_model = User
except (ImportError, AttributeError):
    user_model = User


class Response(models.Model):

    """
    A Response object is a collection of questions and answers with a
    unique interview uuid.
    """

    created = models.DateTimeField(_("Creation date"), auto_now_add=True)
    updated = models.DateTimeField(_("Update date"), auto_now=True)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, verbose_name=_("Survey"), related_name="responses")
    user = models.ForeignKey(user_model, on_delete=models.SET_NULL, verbose_name=_("User"), null=True, blank=True)
    interview_uuid = models.CharField(_("Interview unique identifier"), max_length=36)
    number_of_responses_per_page = models.PositiveSmallIntegerField(null=True, blank=True, default=5)

    class Meta:
        verbose_name = _("Response")
        verbose_name_plural = _("Responses")

    def __str__(self):
        msg = f"Response to {self.survey} by {self.user}"
        msg += f" on {self.created}"
        return msg

questionnaire/views/confirm_view.py
# -*- coding: utf-8 -*-

from django.views.generic import TemplateView

from questionnaire.models import Response
from questionnaire.tasks import send_an_email_about_the_end_of_the_survey


class ConfirmView(TemplateView):

    template_name = "questionnaire/confirm.html"

    def get(self, request, *args, **kwargs):
        response = Response.objects.get(interview_uuid=kwargs["uuid"])
        response_pk = response.survey.pk
        send_an_email_about_the_end_of_the_survey.delay(response_pk)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ConfirmView, self).get_context_data(**kwargs)
        context["uuid"] = str(kwargs["uuid"])
        context["response"] = Response.objects.get(interview_uuid=context["uuid"])
        return context

questionnaire/views/index_view.py
# -*- coding: utf-8 -*-
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView

from questionnaire.models import Survey


# WORKS
class IndexView(LoginRequiredMixin, ListView):
    template_name = "questionnaire/list.html"
    model = Survey
    context_object_name = 'surveys'

questionnaire/views/survey_completed.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from questionnaire.models import Survey


class SurveyCompleted(TemplateView):

    template_name = "questionnaire/completed.html"

    def get_context_data(self, **kwargs):
        context = {}
        survey = get_object_or_404(Survey, is_published=True, slug=kwargs["slug"])
        context["survey"] = survey
        return context

questionnaire/views/survey_detail.py
# -*- coding: utf-8 -*-
import logging

from django.conf import settings
from django.shortcuts import redirect, render, reverse, get_object_or_404
from django.views.generic import View

from questionnaire.decorators import survey_available
from questionnaire.forms import ResponseForm
from questionnaire.models import Survey

LOGGER = logging.getLogger(__name__)


class SurveyDetail(View):
    @survey_available
    def get(self, request, *args, **kwargs):

        survey = get_object_or_404(
            Survey.objects.prefetch_related("questions", "questions__category"), is_published=True,
            slug=kwargs["slug"]
        )

        # survey = kwargs.get("survey")
        step = kwargs.get("step", 0)
        if survey.template is not None and len(survey.template) > 4:
            template_name = survey.template
        else:
            if survey.is_all_in_one_page():
                template_name = "questionnaire/one_page_survey.html"
            else:
                template_name = "questionnaire/survey.html"
        if survey.need_logged_user and not request.user.is_authenticated:
            return redirect("%s?next=%s" % (settings.LOGIN_URL, request.path))

        form = ResponseForm(survey=survey, user=request.user, step=step)
        categories = form.current_categories()

        asset_context = {
            # If any of the widgets of the current form has a "date" class, flatpickr will be loaded into the template
            "flatpickr": any([field.widget.attrs.get("class") == "date" for _, field in form.fields.items()])
        }

        step_now = step + 1

        context = {
            "response_form": form,
            "survey": survey,
            "categories": categories,
            "step": step,
            "asset_context": asset_context,
            "step_now": step_now,
            "steps_count": len(survey.questions.all())
        }

        return render(request, template_name, context)

    @survey_available
    def post(self, request, *args, **kwargs):
        survey = kwargs.get("survey")
        if survey.need_logged_user and not request.user.is_authenticated:
            return redirect("%s?next=%s" % (settings.LOGIN_URL, request.path))

        form = ResponseForm(request.POST, survey=survey, user=request.user, step=kwargs.get("step", 0))
        categories = form.current_categories()

        if not survey.editable_answers and form.response is not None:
            LOGGER.info("Redirects to survey list after trying to edit non editable answer.")
            return redirect(reverse("questionnaire:survey-list"))
        context = {"response_form": form, "survey": survey, "categories": categories}
        if form.is_valid():
            return self.treat_valid_form(form, kwargs, request, survey)
        return self.handle_invalid_form(context, form, request, survey)

    @staticmethod
    def handle_invalid_form(context, form, request, survey):
        LOGGER.info("Non valid form: <%s>", form)
        if survey.template is not None and len(survey.template) > 4:
            template_name = survey.template
        else:
            if survey.is_all_in_one_page():
                template_name = "questionnaire/one_page_survey.html"
            else:
                template_name = "questionnaire/survey.html"
        return render(request, template_name, context)

    def treat_valid_form(self, form, kwargs, request, survey):
        session_key = "survey_%s" % (kwargs["slug"],)
        if session_key not in request.session:
            request.session[session_key] = {}
        for key, value in list(form.cleaned_data.items()):
            request.session[session_key][key] = value
            request.session.modified = True
        next_url = form.next_step_url()
        response = None
        if survey.is_all_in_one_page():
            response = form.save()
        else:
            # when it's the last step
            if not form.has_next_step():
                save_form = ResponseForm(request.session[session_key], survey=survey, user=request.user)
                if save_form.is_valid():
                    response = save_form.save()
                else:
                    response = save_form.save()
                    LOGGER.warning("A step of the multipage form failed but should have been discovered before.")
        # if there is a next step
        if next_url is not None:
            return redirect(next_url)
        del request.session[session_key]
        if response is None:
            return redirect(reverse("questionnaire:survey-list"))
        next_ = request.session.get("next", None)
        if next_ is not None:
            if "next" in request.session:
                del request.session["next"]
            return redirect(next_)
        return redirect("questionnaire:survey-confirmation", uuid=response.interview_uuid)
        # return redirect(reverse('questionnaire:survey-confirmation', args=(response.interview_uuid, )))

questionnaire/views/survey_result.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect

from questionnaire.exporter.csv.survey2csv import Survey2Csv

from questionnaire.models import Survey


def serve_unprotected_result_csv(survey):
    """ Return the csv corresponding to a survey. """
    survey_to_csv = Survey2Csv(survey)
    if survey_to_csv.need_update():
        survey_to_csv.generate_file()
    with open(survey_to_csv.filename, "r") as csv_file:
        response = HttpResponse(csv_file.read(), content_type="text/csv")
    content_disposition = 'attachment; filename="{}.csv"'.format(survey.name)
    response["Content-Disposition"] = content_disposition
    return response


@login_required
def serve_protected_result(request, survey):
    """ Return the csv only if the user is logged. """
    return serve_unprotected_result_csv(survey)


def serve_result_csv(request, primary_key):
    """... only if the survey does not require login or the user is logged.

    :param int primary_key: The primary key of the survey."""
    survey = get_object_or_404(Survey, pk=primary_key)
    if not survey.is_published:
        messages.error(request, "This survey has not been published")
        return redirect("%s?next=%s" % (settings.LOGIN_URL, request.path))
    if survey.need_logged_user:
        return serve_protected_result(request, survey)
    return serve_unprotected_result_csv(survey)

templates/questionnaire/base.html
{% load static %}


<!DOCTYPE html>

<html lang="en">
  <head>
	<meta charset="utf-8">
	<title>{% block title %}{% endblock title %}</title>
    <link rel="icon" href="{% static 'common/img/favicon.ico'%}"/>
    <link href="{% static 'survey/css/bootstrap.min.css'%}" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'survey/css/custom.css' %}" />
<!--    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">-->

{% block extracss %}{% endblock %}

<style type="text/css">

{% block style %}


body {
    height: 100%;
    background: url({% static "common/img/bg1.jpg" %}) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    background-attachment: fixed;
       }
ul {
    font-weight: normal;
    color: red;
}

li {
    font-weight: normal;
    color: red;
}

{% endblock %}


</style>

  </head>
  <body>
  <div id="page_1">
        <div class="container" id="wrap" style="text-align: left;padding-left: 10px;margin-top: 80px;font: 20px 'Roboto';line-height: 25px;">

            {% block background %}
            {% endblock %}

            {% block wrapper %}
            {% endblock %}

            {% block body %}
            {% endblock %}

        </div>

        <div class="container" id="wrap2" style="text-align: left;padding-left: 0px;margin-top: 0px;font: 20px 'Roboto';line-height: 25px;">
            {% block pdf_body %}
            {% endblock %}
        </div>

        <div class="footer">
        <div class="container">
         {% block footer %}{% endblock %}
        </div>
        </div>
      <script type="text/javascript" src="{% static 'survey/js/jquery.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'survey/js/jquery-ui.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'survey/js/bootstrap.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'survey/js/custom.js' %}"></script>
      {% block extrajs %}{% endblock %}
 </div>
</body>
</html>

templates/questionnaire/completed.html
{% extends 'questionnaire/base.html' %}
{% load i18n %}

{% block title %} {% trans "Survey completed" %}{% endblock title %}

{% block body %}
<h1>{% trans "Survey completed" %}</h1>
<p> {% trans "Sorry! Your already replied to our survey" %} "{{ survey.name }}". </p>
<p> <a href="{% url 'questionnaire:survey-list' %}">{% trans "Back to survey list" %}</a> </p>

<input type=button class="btn btn-default btn-lg" style="opacity: 0.8;" value="Previous page" onClick="javascript:history.go(-1);">
{% endblock %}

templates/questionnaire/confirm.html
{% extends 'questionnaire/base.html' %}
{% load i18n %}
{% load static %}

{% block style %}
body {
    height: 100%;
    background: url({% get_media_prefix %}{{ response.survey.bg_image.image }}) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    background-attachment: fixed;
       }
{% endblock %}

{% block title %}{% trans "Survey submitted" %}{% endblock title %}

{% block body %}
<h1>{% if response.survey.global_text %}{{ response.survey.global_text.survey_submitted }}{% else %}{% trans "Survey submitted"%}{% endif %}</h1>
<p>
    <div class="alert alert-success">
       {% if response.survey.global_text %}{{ response.survey.global_text.answers_have_been_saved }}{% else %}{% trans "Thanks! Your answers have been saved" %}{% endif %}
    </div>
    {% if response.survey.editable_answers %}
        <div class="alert alert-info">
           {% if response.survey.global_text %}{{ response.survey.global_text.you_can_change_answers }}{% else %}{% trans "You can always come back and change them." %}{% endif %}
        </div>
    {% endif %}
</p>
{% if response.survey.editable_answers%}
<a href="{% url 'questionnaire:survey-detail' slug=response.survey.slug %}"><input type="button" class="btn btn-default btn-lg" style="opacity: 0.8;" value="{% if response.survey.global_text %}{{ response.survey.global_text.button_start_over }}{% else %}Start over{% endif %}"></a>
{% endif %}
{% endblock %}

templates/questionnaire/list.html
{% extends 'questionnaire/base.html' %}
{% load i18n %}

{% block title %}
Marketing monkeys
{% endblock title %}

{% block body %}
<div id="intro">
	<h1 style="color: white;"><strong>Survey app</strong></h1><br>

		<ul>
			{% for survey in surveys %}

				<li style="color: white;"><a style="color: purple;" href="{% url 'questionnaire:survey-detail' slug=survey.slug %}"><strong>{{survey.name}}</strong></a></li>

			{% endfor %}
		</ul>

</div>
{% endblock %}

templates/questionnaire/one_page_survey.html
{% extends 'questionnaire/survey.html' %}

templates/questionnaire/question.html
{% load bootstrap %}
{% load survey_extras %}

<table class="table table-hover" style="font-weight: 100;">
    <!--<thead>
      <tr>
        <th> Question  </th>
        <th> Answers </th>
      </tr>
    </thead> -->
    <tbody>
<div class="btn-group" data-toggle="buttons">
{% for form in response_form %}
	{% if form.field.widget.attrs.category == category.name or not form.field.widget.attrs.category %}
        <tr class="{% if form.errors%} danger {% endif %}">
            <td>
	            <b style="padding-bottom: 40px; font-size: 20pt;">{{ form.label|safe }}</b><br>
	            {% if form.field.required %}
	                <span class="glyphicon glyphicon-asterisk" style="color:red"> </span>
	            {% endif %}
	            <span class="help-inline" style="color:red">
	                <strong> {% for error in  form.errors %}{{ error }}{% endfor %} </strong>
	            </span> <br>
                {% if form.field.widget.input_type == 'select' %}
                <select name="{{form.name}}"{% if form.field.widget.attrs.disabled %} disabled{% endif %}>
                {% endif %}

	            {% for field in form %}

                    {% if field.tag and field.choice_label %}<label style="font-weight: normal;">{{ field.tag }} {{ field.choice_label }}<br></label>{% else %}{{ field }}{% endif %}<br>


                {% endfor%}

                {% if form.field.widget.input_type == 'select' %}
                </select>
                {% endif %}
            </td>
        </tr>
	{% endif %}
{% endfor %}
    </div>
    </tbody>
</table>

templates/questionnaire/survey.html
{% extends 'questionnaire/base.html' %}
{% load i18n %}
{% load survey_extras %}
{% load static %}


{% block style %}
body {
    height: 100%;
    background: url({% get_media_prefix %}{{ survey.bg_image.image }}) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    background-attachment: fixed;
       }
{% endblock %}


{% block title %}
Marketing monkeys
{% endblock title %}

{% block extrajs %}
  {{response_form.media}}
  {% if asset_context.flatpickr %}
    <script type="text/javascript" src="{% static 'survey/js/flatpickr.min.js' %}"></script>
  {% endif %}
{% endblock %}

{% block extracss %}
  {% if asset_context.flatpickr %}
    {{ block.super }}
    <link href="{% static 'survey/css/flatpickr.min.css'%}" rel="stylesheet" type="text/css"/>
  {% endif %}
{% endblock %}



{% block body %}
	<h1 style="color: white;"><strong>{{survey.name}}</strong></h1>
	<div class="survey-description" style="font-style: oblique;"><strong>{{survey.description|safe}}</strong></div>
	<div>
      {% if step and step != 0 %}
		<h3>{% if survey.global_text %}{{ survey.global_text.question }}{% else %}question{% endif %} {{ step_now }} of {{ steps_count }}</h3>
		<form action="{% url 'questionnaire:survey-detail-step' slug=survey.slug step=step %}" method="post">
	{% else %}
		<form action="{% url 'questionnaire:survey-detail' slug=survey.slug %}" method="post">
	{% endif %}
	{% if step == 0 %} <h3>{% if survey.global_text %}{{ survey.global_text.question }}{% else %}question{% endif %} 1 of {{ steps_count }}</h3> {% endif %}
	    {% csrf_token %}
        {% for category in categories %}
			<br>
<!--            <h3> {{category}} </h3>-->
<!--            <p> {{category.description}} </p>-->
			<div class="panel-group" id="accordion" style="opacity: 0.8;">
				<div class="panel panel-default">
				    <div class="panel-heading">
				        <h3 class="panel-title"> <a
				        data-toggle="collapse show"
				        data-parent="#accordion"
				        href="#collapse{{category.slugify}}">
				            {% if survey.global_text %}{{ survey.global_text.answer_this_part }}{% else %}{% trans "Answer this part" %}{% endif %}
			            </a></h3>
				    </div>
                    <div class="category-container">
				        <div id="collapse{{category.slugify}}" class="panel-collapse collapse show {% if not survey.editable_answers and response_form.response is not None %}in{% endif %}
				        {{ response_form|collapse_form:category }}">
				            <div class="panel-body">
	                           {% include "questionnaire/question.html" %}
                            </div>
		                </div>
                </div>
            </div>
        {% empty %}
            <h3> {% trans "Questions" %} </h3>
            {% include "questionnaire/question.html" %}
        {% endfor %}

        <br>
		{% if survey.editable_answers or response_form.response is None %}
	    {% if response_form.has_next_step %}
				    {% if step and step != 0 %}<input type=button class="btn btn-default btn-lg" style="margin-right: 10px;" value="{% if survey.global_text %}{{ survey.global_text.button_previous_page }}{% else %}Previous page{% endif %}" onClick="javascript:history.go(-1);">{% endif %}<input
  			          class="btn btn-default btn-lg"
				        type="submit"
				        value="{% if survey.global_text %}{{ survey.global_text.button_next }}{% else %}{% trans "Next" %}{% endif %}"
        			>
				{% else %}
				    <input type=button class="btn btn-default btn-lg" style="margin-right: 10px;" value="{% if survey.global_text %}{{ survey.global_text.button_previous_page }}{% else %}Previous page{% endif %}" onClick="javascript:history.go(-1);"><input
  			          class="btn btn-default btn-lg"
				        type="submit"
				        value="{% if survey.global_text %}{{ survey.global_text.button_done }}{% else %}{% trans "I'm done" %}{% endif %}"
        			>

				{% endif %}
		{% endif %}
	</form></div>
{% endblock %}

templates/questionnaire/view_result_pdf_file.html
{% extends 'questionnaire/base.html' %}
{% load i18n %}
{% load static %}
{% load survey_extras %}


{% block style %}

#p1dimg1 {position:absolute;top:0;left:0px;z-index:-1; width:1204px;height:1585px;}
#p1dimg1 #p1img1 {position:absolute;top:-90px;left:0px;z-index:-1; width:1204px;height:1695px;opacity: 0.25;}


{% endblock %}


{% block pdf_body %}
{% for questions_block in questions_blocks %}
<div id="intro" style="margin-top: 1px; position: relative;" xmlns="http://www.w3.org/1999/html">

	{% if forloop.first %}
		<h1 class="h1_1" style=
				"text-align: center;
				color: #4B0082 !important;
<!--				border-bottom-style: solid; -->
				padding: 10px;">
			<strong style="color: #4B0082 !important;">Results for "{{survey}}"</strong>
		</h1><br>
	{% endif %}


		<DIV id="p1dimg1">
			{{ survey.bg_image.image_code|safe }}
		</DIV>

		<DIV style="margin-top:90px;">
		</DIV>

		<DIV style="position: absolute;">
		<ul>
			{% for question in questions_block %}

				<li style="opacity: 0.9;"><h3 id="question"><strong style="color: #191970 !important;">Question: </strong><em style="font-style: italic;">{{question.text}}</em></h3>

					{% for answer in question.answers.all %}

							<p><strong style="color: purple !important;">Answer: </strong><b style="font-style: italic;">{{answer.body}}</b></p><br>

					{% endfor %}
				</li>

			{% endfor %}
		</ul>
		</DIV>

		{% if not forloop.last %}
			<div style="page-break-after: always;"></div>
		{% endif %}

</div>
{% endfor %}
{% endblock %}